version: 2
jobs:
  build:
    macos:
      xcode: 10.1.0
   working_directory: /Users/distiller/project
   environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
    - checkout
    - run:
        name: Build and run tests
        command: fastlane scan
    - store_test_results:
        path: test_output/report.xml
    - store_artifacts:
        path: /tmp/test-results
        destination: scan-test-results
    - store_artifacts:
        path: ~/Library/Logs/scan
        destination: scan-logs
workflows:
  version: 2
  workflow:
    jobs:
    - build
